# Generated by Django 4.1.10 on 2023-11-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("movie_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("genre", models.CharField(max_length=255)),
                ("storyline", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MovieReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=255)),
                ("review_id", models.IntegerField()),
                ("review_title", models.CharField(max_length=255)),
                ("review_content", models.CharField(max_length=255)),
                ("imdb_rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MovieReviewRelated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_sci.moviedescription",
                    ),
                ),
                (
                    "movie_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_sci.moviereview",
                    ),
                ),
            ],
        ),
    ]
