# Generated by Django 4.1.10 on 2023-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0002_rename_imdb_rating_moviereview_imbd_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviedescription",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
