# Generated by Django 4.1.10 on 2023-11-03 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0005_alter_moviedescription_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviedescription",
            name="rank",
        ),
    ]
