# Generated by Django 4.1.10 on 2023-11-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0006_remove_moviedescription_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="review_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moviereview",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
    ]
