# Generated by Django 4.1.10 on 2023-11-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0008_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.AddField(
            model_name="moviereview",
            name="sentiment",
            field=models.CharField(default="Neutral", max_length=20),
            preserve_default=False,
        ),
    ]
