# Generated by Django 4.1.10 on 2023-11-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0009_delete_comment_moviereview_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Neutral", "Neutral"),
                ],
                max_length=20,
            ),
        ),
    ]
