# Generated by Django 4.1.10 on 2023-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0010_alter_moviereview_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="sentiment",
            field=models.CharField(max_length=20),
        ),
    ]
