# Generated by Django 4.1.10 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0012_remove_moviereview_review_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviereview",
            name="imbd_rating",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
