# Generated by Django 4.1.10 on 2023-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0013_alter_moviereview_imbd_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newcomment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_comment", models.CharField(max_length=255)),
            ],
        ),
    ]
