# Generated by Django 4.1.10 on 2023-11-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0014_newcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Newcomment",
        ),
    ]
