# Generated by Django 4.1.10 on 2023-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0015_comment_delete_newcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
