# Generated by Django 4.1.10 on 2023-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0016_alter_comment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                ("sentiment", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
