# Generated by Django 4.1.10 on 2023-11-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_sci", "0018_comment_delete_usercomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.CharField(max_length=20)),
                ("sentiment", models.CharField(max_length=20)),
            ],
        ),
    ]
